name: PR Coverage Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Run unittests with coverage
      run: |
        coverage run --rcfile=.coveragerc -m unittest discover -s tests
        coverage xml

    - name: Comment PR with coverage
      uses: orgoro/coverage@v3.2
      with:
        coverage-file: coverage.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}